esphome:
  name: nodelsi
  friendly_name: NodeLSI

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "pErvZebyiC5eMa34L2KKwqdbx4/5UDIy0fZSTaMcuCE="

ota:
  password: "f3ad423a7c1e8c9a893d37974e0f490d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nodelsi Fallback Hotspot"
    password: "FJhzVmRTNQP1"

captive_portal:

switch:
  - platform: gpio
    pin:
      number: 2
      inverted: True
    name: "led interno"
    id: "ledinterno"

sensor:
  - platform: adc
    pin: 
      number: A0
      inverted: True
    name: "LDR"
    filters:
      - multiply: 3.3
    update_interval: 15s

  - platform: dht
    pin: GPIO14
    model: DHT11
    temperature:
      name: "Temperatura"
    humidity:
      name: "Umidade"
    update_interval: 15s
    

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO12
      inverted: True
      mode:
        input: true
        pullup: true
    name: "Fumaça"

# remote_transmitter:
#   - platform: template
#     name: "Teste IR"
#     on_press:
#     - remote_transmitter.transmit_raw:
#           code: [4088, -1542, 1019, -510, 513, -1019, 510, -509, 511, -510, 1020,
#                 -1020, 1022, -1019, 510, -509, 511, -510, 511, -509, 511, -510,
#                 1020, -1019, 510, -511, 1020, -510, 512, -508, 510, -1020, 1022,
#                 -1021, 1019, -1019, 511, -510, 510, -510, 1022, -1020, 1019,
#                 -1020, 511, -511, 1018, -1022, 1020, -1019, 1021, -1019, 1020,
#                 -511, 510, -1019, 1023, -1019, 1019, -510, 512, -508, 510, -511,
#                 512, -1019, 510, -509]